import Promobar from "@/components/layout/Promobar";
import "./globals.css";
import localFont from 'next/font/local'
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const integralCF = localFont({
  src: [
    {
      path: '../../public/fonts/Integral-CF-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Integral-CF-Regular.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-integral', // CSS variable name
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${integralCF.variable} font-sans text-black`}>
        <div className="bg-black">
          <Promobar />
        </div>
        <Navbar />
        <div >
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
